site_name: Movimiento Animal
#site_url: https://pvilas.github.io/animal-movements/
site_url: http://movimiento-animal.es/
site_description: Compilación de movimientos animales con detalles de cada ejercicio, rutinas, etc.
site_author: Pere Vilás (https://github.com/pvilas)
copyright: Pere Vilás
extra:
    version: 1.0
    posters: '/img/posters/'
    # disqus: movimiento-animal
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/pvilas
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/pvilas/
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/perevilas
#extra_css:
#  - stylesheets/fonts.css          
theme:
    name: material
    language: es
    custom_dir: overrides
    logo: img/logo.png
    favicon: favicon.ico
plugins:
  - macros    
copyright: '@Pere Vilás (<a href="http://pvilas.com" target="_blank">pvilas.com</a>)'
markdown_extensions:
  - meta
  - attr_list
nav:
- Home : 'index.md'
- Calentar:
    - 'El calentamiento' : 'calentar/index.md'        
    - 'Pies y tobillos' : 'calentar/pies.md'
    - 'Rodillas' : 'calentar/rodillas.md'
    - 'Caderas' : 'calentar/caderas.md' # falten rotacions de peus
    - 'Brazos' : 'calentar/brazos.md'
    - 'Cuello' : 'calentar/cuello.md'
    - 'Espina' : 'calentar/calentar_espina.md'
    - 'Estirar hombros' : 'calentar/estirar_hombros.md'
- Ejercicios:
    - 'Los ejercicios': 'ejercicios/index.md'
    - 'Push Up': 'ejercicios/pushup.md'
    - 'El arquero': 'ejercicios/arquero.md'
    - 'El arquero bajo' : 'ejercicios/arquero_bajo.md'
    - 'Hanuman Dand' : 'ejercicios/pushup_pie_adelantado.md'
    - 'Drill para lizard' : 'ejercicios/drill_para_lizard.md'
    - 'Pushup un brazo': 'ejercicios/pushup_un_brazo.md'
    - 'Pushup combo': 'ejercicios/pushup_combo.md'    
    - 'Flexión hindú' : 'ejercicios/flexion_hindu.md'
    - 'La pica' : 'ejercicios/pica.md'
    - 'Levantamiento de pies' : 'ejercicios/levantamiento.md'    
- Animales:
    - 'Los animales': 'animales/index.md'
    - 'El gatito': 'animales/gatito.md'
    - 'Araña frontal': 'animales/aranya_frontal.md'
    - 'Araña lateral': 'animales/aranya_lateral.md'
    # - El oso
    - 'El caimán': 'animales/soldado.md'
    - 'El chimpancé': 'animales/chimpance.md'
    - 'Lagartija alta' : 'animales/high_lizard.md'
    - 'La lagartija' : 'animales/lizard.md'
    - 'El triángulo': 'animales/triangulo.md'
    # - gusano frontal
    - 'El balancín': 'animales/balancin.md'
    # rana (adelante, atras)
    # escorpión
    # - avanzar de culo - el grillo
    # cangrejo (boca amunt sobre quatre pates)
    # puente
    - Gambas:
        - 'Las gambas': 'animales/gambas/index.md'
        - 'Gamba hacia atrás': 'animales/gambas/gamba_atras.md'
        - 'Gamba hacia adelante': 'animales/gambas/gamba_adelante.md'
        - 'Gamba lateral': 'animales/gambas/gamba_de_lado.md'
    # - Ranas:
    - Cambios de base:            
        - 'Los cambios de base': 'animales/base/index.md'
        #    - 'Rotar': 'animales/base/rotar.md'
        - 'Cambio de base lateral': 'animales/base/cambio_base_lateral.md'
        - 'Cambio de base frontal': 'animales/base/cambio_base_frontal.md'
        - 'Levantada técnica': 'animales/base/levantada_tecnica.md'    
# - Caminar:  conscient (avant, darrera), de costat (Tai Chi Chuan), samba, dragón, ninja, pas de chat, tsudan tsuki, shomen-uchi, yokomen-uchi
# shikko (aikido), kaiten-shikko
# Rodar
# https://www.youtube.com/watch?v=8xsrIua53L8
- Enfriar:    
    - 'El enfriamiento' : 'enfriar/index.md'
    # - la foca
    - 'El pino' : 'enfriar/pino.md'
    - 'Psoas' : 'enfriar/psoas.md'
    - 'Sarvangasana' : 'enfriar/sarvangasana.md'    
    - 'Sirsasana' : 'enfriar/sirsasana.md'
    # meditar    
- Varios:    
    # - 'Notas': 'varios/notas.md'
    - 'Recopilación inicial': 'varios/recopilacion.md'
    - 'Mis videos de Pilates': 'varios/pilates.md'
    # - 'Mkdocs': 'varios/mkdocs.md'
    - 'Fuentes': 'varios/fuentes.md'
    - 'Próximamente': 'varios/proximamente.md'
    - 'Libros': 'varios/libros.md'
    - 'Plantilla de ejercicio': 'plantillas/ejercicio.md'    
    - 'Entorno': 'varios/variables.md'