site_name: movimiento-animal.es
site_url: https://movimiento-animal.es/
site_description: Sitio web de locomoción y movimiento animal. Detalles de cada ejercicio, rutinas, etc.
site_author: Pere Vilás (https://github.com/pvilas)
copyright: Pere Vilás
extra:
    version: 1.0
    posters: '/img/posters/'
    yandex_verification: 'dea5f349dc0d400a'
    # ms_verification: '39CD457F50BFFB380B0EB7C2DDA1B4DE'
    # disqus: movimiento-animal
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/pvilas
        - icon: fontawesome/brands/linkedin
          link: https://www.linkedin.com/in/pvilas/
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/movimientoanim4
extra_css:
  - stylesheets/fonts.css          
theme:
    name: material
    language: es
    custom_dir: overrides
    logo: https://static.movimiento-animal.es/img/logo.png
    favicon: favicon.ico
    palette:
      scheme: default
    features:
        - navigation.tabs
        - navigation.sections        
plugins:
  - macros
  - search:
      lang: es      
copyright: '@Pere Vilás (<a href="http://pvilas.com" target="_blank">pvilas.com</a>)'
markdown_extensions:
  - meta
  - attr_list
  - pymdownx.emoji:      
      emoji_generator: !!python/name:materialx.emoji.to_svg  
arrel_img: "https://static.movimiento-animal.es/"
nav:
- Home : 'index.md'
- Calentar:
    - 'El calentamiento' : 'calentar/index.md'        
    - 'Pies y tobillos' : 'calentar/pies.md'
    - 'Rodillas' : 'calentar/rodillas.md'
    - 'Caderas' : 'calentar/caderas.md' # falten rotacions de peus
    - 'Brazos' : 'calentar/brazos.md'
    - 'Cuello' : 'calentar/cuello.md'
    - 'Espina' : 'calentar/calentar_espina.md'
    - 'Estirar hombros' : 'calentar/estirar_hombros.md'
    - 'Burpees': 'calentar/burpees.md'
- Locomoción:
    - "Índice": "locomocion/index.md"
    - Animales:
        - 'Los animales': 'locomocion/animales/index.md'
        - 'El gato': 'locomocion/animales/gato.md'
        - 'Araña frontal': 'locomocion/animales/aranya_frontal.md'
        - 'Araña lateral': 'locomocion/animales/aranya_lateral.md'
        - 'El oso': 'locomocion/animales/oso.md'
        - 'El cangrejo': 'locomocion/animales/cangrejo.md'
        - 'La esfinge': 'locomocion/animales/esfinge.md'
        - 'El grillo': 'locomocion/animales/grillo.md'
        - 'Perro perezoso': 'locomocion/animales/perro-perezoso.md'
        - 'El caimán': 'locomocion/animales/caiman.md'
        - 'El chimpancé': 'locomocion/animales/chimpance.md'
        - 'Lagartija alta' : 'locomocion/animales/lagartija_alta.md'
        - 'La lagartija' : 'locomocion/animales/lagartija.md'
        - 'El triángulo': 'locomocion/animales/triangulo.md'
        # - gusano frontal
        - 'El balancín': 'locomocion/animales/balancin.md'
        # rana (adelante, atras)
        # escorpión
        # - avanzar de culo - el grillo
        # cangrejo (boca amunt sobre quatre pates)
        # puente
    - Caminar:
        - 'Caminar': 'locomocion/caminar/index.md'
        - 'Arquero de pie': 'locomocion/caminar/arquero_de_pie.md'
        - 'Recoger del suelo': 'locomocion/caminar/recoger_del_suelo.md'
        - 'Buenos días': 'locomocion/caminar/buenos_dias.md'
        - 'El ruso': 'locomocion/caminar/el_ruso.md'
        - 'El bailarín': 'locomocion/caminar/estiramiento_psoas.md'
        - 'Puñetazo en pie': 'locomocion/caminar/punyetazo_en_el_pie.md'
        - 'Rotación caderas 1p.': 'locomocion/caminar/rotacion_caderas_sobre_una_pierna.md'
    - Gambas:
        - 'Las gambas': 'locomocion/gambas/index.md'
        - 'Gamba hacia atrás': 'locomocion/gambas/gamba_atras.md'
        - 'Gamba hacia adelante': 'locomocion/gambas/gamba_adelante.md'
        - 'Gamba lateral': 'locomocion/gambas/gamba_de_lado.md'
    # - Ranas:
    - Cambios de base:            
        - 'Los cambios de base': 'locomocion/base/index.md'
        #    - 'Rotar': 'animales/base/rotar.md'
        - 'Cambio de base lateral': 'locomocion/base/cambio_base_lateral.md'
        - 'Cambio de base frontal': 'locomocion/base/cambio_base_frontal.md'
        - 'Levantada técnica': 'locomocion/base/levantada_tecnica.md'    
    # - Caminar:  conscient (avant, darrera), de costat (Tai Chi Chuan), samba, dragón, ninja, pas de chat, tsudan tsuki, shomen-uchi, yokomen-uchi
    # shikko (aikido), kaiten-shikko
    # Rodar
    # https://www.youtube.com/watch?v=8xsrIua53L8
    - Tecnificación:
        - 'Los ejercicios': 'locomocion/ejercicios/index.md'
        - 'Push Up': 'locomocion/ejercicios/pushup.md'
        - 'El arquero': 'locomocion/ejercicios/arquero.md'
        - 'El arquero bajo' : 'locomocion/ejercicios/arquero_bajo.md'
        - 'Hanuman Dand' : 'locomocion/ejercicios/pushup_pie_adelantado.md'
        - 'Prep. Lagartija' : 'locomocion/ejercicios/drill_para_lizard.md'
        - 'Pushup un brazo': 'locomocion/ejercicios/pushup_un_brazo.md'
        - 'Pushup combo': 'locomocion/ejercicios/pushup_combo.md'    
        - 'Flexión hindú' : 'locomocion/ejercicios/flexion_hindu.md'
        - 'La pica' : 'locomocion/ejercicios/pica.md'
        - 'Levantamiento de pies' : 'locomocion/ejercicios/levantamiento.md'    
- Enfriar:    
    - 'El enfriamiento' : 'enfriar/index.md'
    # - la foca
    - 'El pino' : 'enfriar/pino.md'
    - 'Psoas' : 'enfriar/psoas.md'
    - 'Sarvangasana' : 'enfriar/sarvangasana.md'    
    - 'Sirsasana' : 'enfriar/sirsasana.md'
    # meditar    
- Series:
    - 'Dolor lumbar': 'series/quitar_dolor_lumbar.md'
- Jiu-jitsu:
    - 'Índice': 'jujutsu/index.md'
    - Escapes:
        - 'Bàsics': 'jujutsu/escapes/index.md'
        - 'Monta': 'jujutsu/escapes/monta.md'
        - 'Baralla de peus': 'jujutsu/escapes/peus.md'
        - 'Side control': 'jujutsu/escapes/side.md'
        - 'Knee escape': 'jujutsu/escapes/knee.md'
        - 'Kesa Gatame': 'jujutsu/escapes/kesa.md'
        - 'Reverse Kesa': 'jujutsu/escapes/reversekesa.md'
        - 'Knee on belly': 'jujutsu/escapes/belly.md'
        - 'North/south':  'jujutsu/escapes/ns.md'
    - Guard Retention:
        - 'Bàsics': 'jujutsu/retention/index.md'        
        - 'Seated': 'jujutsu/retention/seated.md'
        - 'Supine': 'jujutsu/retention/supine.md'
        - 'Turtle': 'jujutsu/retention/turtle.md'
        - 'Frames': 'jujutsu/retention/frames.md'
        - 'Demarcation': 'jujutsu/retention/demarcation.md'
        - 'Connection': 'jujutsu/retention/connection.md'
        - 'Filosofia': 'jujutsu/retention/filosofia.md'
        - 'Double under': 'jujutsu/retention/especifics-double-under.md'
        - 'Over under': 'jujutsu/retention/especifics-over-under.md'
        - 'Toreando': 'jujutsu/retention/especifics-toreando.md'
        - 'Leg drag': 'jujutsu/retention/especifics-leg-drag.md'
        - 'Long step': 'jujutsu/retention/especifics-long-step.md'
        - 'Shift': 'jujutsu/retention/especifics-cranial-shift.md'
    - Juji:
        - 'Bàsics': 'jujutsu/juji/index.md'
        - 'Tancada': 'jujutsu/juji/tancada.md'
        - 'Tancada malic': 'jujutsu/juji/malic.md'    
- Varios:    
    - 'Índice': 'varios/index.md'
    - 'Recopilación inicial': 'varios/recopilacion.md'
    - 'Mis videos de Pilates': 'varios/pilates.md'
    # - 'Mkdocs': 'varios/mkdocs.md'
    - 'Fuentes': 'varios/fuentes.md'
    - 'Próximamente': 'varios/proximamente.md'
    # - 'Libros': 'varios/libros.md'
    - 'Plantilla': 'varios/plantilla.md'
    - 'Legal': 'varios/legal.md' 
    - 'Privacidad': 'varios/privacidad.md'        
    - 'Cookies': 'varios/cookies.md'
    - 'Entorno': 'varios/variables.md'